// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Day1$Aoc2018 = require("./Day1.bs.js");

describe("Day 1", (function () {
        Jest.test("Part 1", (function (param) {
                return Jest.Expect[/* toBe */2](466, Jest.Expect[/* expect */0](Day1$Aoc2018.solve1(/* () */0)));
              }));
        Jest.test("Part 2", (function (param) {
                return Jest.Expect[/* toBe */2](750, Jest.Expect[/* expect */0](Day1$Aoc2018.solve2(/* () */0)));
              }));
        return Jest.test("Part 2 with streams", (function (param) {
                      return Jest.Expect[/* toBe */2](750, Jest.Expect[/* expect */0](Day1$Aoc2018.solve2Streams(/* () */0)));
                    }));
      }));

/*  Not a pure module */
