// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Day2$Aoc2018 = require("./Day2.bs.js");

describe("Day 2", (function () {
        return Jest.test("Part 1", (function (param) {
                      return Jest.Expect[/* toBe */2](5904, Jest.Expect[/* expect */0](Day2$Aoc2018.solve(/* () */0)));
                    }));
      }));

/*  Not a pure module */
